### ISSUE TITLE
안녕하세요 프로솔브 사용자입니다

### ISSUE THREAD

**Issue by kim-sung-jee** [dev-redo/pro-solve#120]
## 제안하고 싶은 기능을 설명해주세요
제안하고 싶은 기능을 여기에 설명해주세요.

1. 태그별(유형별) 진행도를 추가했으면 합니다.

해당 유형에 대해 어느정도의 숙련도를 갖고있는지 또는
내가 접하지 못한 유형들은 어느 것들이 있는지
판단하는 지표가 될 것 같습니다.

![image](https://user-images.githubusercontent.com/85841791/209887058-ce13dd7a-c672-4736-9c8c-f531fcf72129.png)

2.나의 풀이 페이지에서 마이페이지가 있었으면 좋겠습니다.
프로솔브 만의 마이페이지이든, 프로그래머스 내의 정보와 연동되는 마이페이지이든

현재 진행도 또는 참여도를 보여주는 그런 데이터가 나타났으면 좋겠다는 의견입니다..!

![image](https://user-images.githubusercontent.com/85841791/209887167-9fdd49e0-a447-4d14-9a38-fce11e85dce4.png)

## 추가 설명
추가로 설명하고 싶으신 사항이 있으시다면 여기에 설명해주세요.

읽어주셔서 감사합니다

**Comment by dev-redo** [comment]
@kim-sung-jee 

안녕하세요. 프로솔브에 관심을 주셔서 정말로 감사합니다. 최대한 말씀해주신 기능을 구현하기 위해 노력하겠습니다!
관련 기능에 대해 몇 가지 질문이 있어서 코멘트 남깁니다.

기능 1. 태그별(유형별) 진행도를 추가했으면 합니다.
현재 프로그래머스의 경우 문제 유형이 연습문제, 카카오 문제 등등으로 되어있습니다. 

이중 카카오나 연습문제같은 문제들을 제외하고 그래프, 이분탐색 등등 유형 문제들만 있으시길 바라신지, 아님 포함하시길 바라시는지 여쭈어 보고싶습니다!

(현재 카카오같은 기업 문제들의 경우 년도마다 유형이 나뉘어져있습니다. (ex. 2018년도 카카오, 2020년도 카카오) 만약 포함하시길 원하신다면 년도들을 합쳐서 카카오유형으로 분류하겠습니다!)

UI는 둘다 solved.ac에서 level 그래프와 비슷하게 구현하겠습니다!
(solved.ac level 링크: https://solved.ac/en/problems/level)


기능 2. 나의 풀이 페이지에서 마이페이지가 있었으면 좋겠습니다.

현재 진행도 또는 참여도를 보여주는 데이터를 말씀해주셨는데, 혹시 잔디 기능같은 것을 말씀하시는 것인지 여쭈어보고싶습니다!

만약 맞다면 구현이 힘들 것 같다고 조심스럽게 말씀드립니다..ㅜㅜ 
이전에 잔디 기능을 구현하고자 했으나 현재 프로그래머스 API 중 유저가 언제언제 문제를 풀었는지에 대해 얻을수 있는 API가 없어서 구현을 못했습니다,,! 나중에 프로그래머스에서 관련 데이터를 얻을 수 있는 API가 생기게 된다면 바로 만들어보겠습니다!

<br />


다시 한 번 프로솔브에 대해 많은 관심을 주셔서 정말 감사하다는 말씀 올립니다. 코멘트 기다리겠습니다! 🙇‍♂️

**Comment by kim-sung-jee** [comment]
@dev-redo 

1.그러네요..! 연습문제,기출문제(카카오등)들로만 나뉘어져 있는데
400개가 넘는 문제들을 일일이 수작업으로 태그를 나누기 힘들어 보이기도 하고 무엇보다
문제유형에 관한 태그를 제공(진행도 및 현재상태제공)하다보면
문제를 푸는데 있어 사용자의 관찰력 및 사고력등을 제한시킬 것 같아 걱정이 됩니다()
이건 제가 생각이 짧았네요..!

기출별로 진행도를 나타내는 것도 카카오밖에 없다시피 해서 굳이 나눌 필요는 없을 것 같아요
(제 개인적인 생각입니다.)  나의 풀이 페이지에서 필터링 돼서 검색되기도 하고

2.잔디같은 기능들도 추가할 수 있고 문제마다  자신만의 생각 및 정리같은 것들을 
아카이빙할 수 있게 끔 추가하는 것도 고려해 주시면 감사하겠습니다

3. 문제 페이지에서 LV별 필터링도 추가해주시면 감사하겠습니다..!


읽어주셔서 감사합니다

**Comment by dev-redo** [comment]
@kim-sung-jee 

## 기능 1. 유형 정리 ( - 구현 X)
말씀대로 기능 1은 확실히 백준처럼 유형이 나와있지 않아서 애매한 느낌이 드네요ㅜㅜ

## 기능 2. 문제 아카이빙 (- 구현 O)
오!! 문제 페이지에 생각을 정리할 수 있는 노트같은 기능을 구현해보면 재밌겠네요 ㅎㅎ!! 

## 기능 3 - 나의 풀이 페이지의 "문제" 페이지에 LV 필터링
해당 기능은 LV select 박스를 구현해 원하시는 문제를 선택할 수 있게끔 구현해보겠습니다!

<br />

프로솔브에 자세한 피드백을 주셔서 정말로 감사합니다!
말씀해주신 기능을 빠른 시일 내에 하나씩 구현해 릴리즈하도록 하겠습니다 ㅎㅎ 🙇‍♂️
